vmware/flowgate

flowgate-common/src/main/java/com/vmware/flowgate/common/FlowgateConstant.java

Modify the default expired time to 3 months

---

ui/package-lock.json
ui/package.json

Upgrade the dependencies version of node

---

flowgate-common/pom.xml

Upgrade the version of jackson to 2.9.9

---

ui/package-lock.json
ui/package.json

Upgrade the denpendencies version of ui

---

flowgate-api/src/main/java/com/vmware/flowgate/controller/SystemSettingController.java
ui/src/app/pages/setting/component/trigger-job/trigger-job.component.html
ui/src/app/pages/setting/component/trigger-job/trigger-job.component.ts

Modify the time unit

---

.gitmessage

[Style] Add Signed-off-by to git message

---

flowgate-api/src/main/java/com/vmware/flowgate/controller/AuthController.java
flowgate-api/src/main/java/com/vmware/flowgate/controller/FacilitySoftwareController.java
flowgate-api/src/test/java/com/vmware/flowgate/controller/FacilitySoftwareControllerTest.java
flowgate-common/src/main/java/com/vmware/flowgate/common/FlowgateConstant.java

Refactor the api of query facifitysoftwareconfig

---

flowgate-api/src/test/java/com/vmware/flowgate/controller/SystemSettingControllerTest.java

Fix the issure of systemsetting test case

---

ui/package-lock.json
ui/package.json

upgrade the version of some dependencies

---

flowgate-common/pom.xml

Update Jackson version

---

make/database/init.sh

Correct the sql count number

---

aggregator/src/main/java/com/vmware/flowgate/aggregator/scheduler/job/AggregatorService.java
vro-worker/src/main/java/com/vmware/flowgate/vroworker/scheduler/job/VROAsyncJob.java

Fix the logic error in filter out qualify servers.
Will not update the sensors if the formular is already filled.

Fix sensor-mapping update bug

---

flowgate-common/pom.xml

Update jackson-databind version to 2.9.10

---

ui/package-lock.json
ui/package.json

fix mixin-deep version bug

---

flowgate-common/src/main/java/com/vmware/flowgate/common/model/FacilitySoftwareConfig.java
infoblox-worker/src/main/java/com/vmware/flowgate/infobloxworker/service/InfobloxClient.java

fix issue about infoblox integration add proxy_serach parameters

---

ui/src/app/pages/facility/component/cmdb/cmdb-add/cmdb-add.component.html
ui/src/app/pages/facility/component/cmdb/cmdb-add/cmdb-add.component.ts
ui/src/app/pages/facility/component/cmdb/cmdb-edit/cmdb-edit.component.html
ui/src/app/pages/facility/component/cmdb/cmdb-edit/cmdb-edit.component.ts

Add a section for advance setting in create and edit infoblox pages

---

infoblox-worker/src/main/java/com/vmware/flowgate/infobloxworker/service/InfobloxClient.java
ui/src/app/pages/facility/component/cmdb/cmdb-add/cmdb-add.component.html
ui/src/app/pages/facility/component/cmdb/cmdb-add/cmdb-add.component.ts
ui/src/app/pages/facility/component/cmdb/cmdb-edit/cmdb-edit.component.html
ui/src/app/pages/facility/component/cmdb/cmdb-edit/cmdb-edit.component.ts

Specify the proxy_serach of infoblox

---

ui/src/app/pages/facility/component/cmdb/cmdb-edit/cmdb-edit.component.ts

fix update infoblox issue

---

ui/package.json

upgrade some dependencies

---

make/build.sh
make/maven-docker-build/DockerfileUI
make/maven-docker-build/buildui.sh
make/maven-docker-build/buildui.yml

specify the npm version in buildui.sh

---

flowgate-api/src/main/java/com/vmware/flowgate/controller/FacilitySoftwareController.java
flowgate-api/src/main/java/com/vmware/flowgate/repository/FacilitySoftwareConfigRepository.java
flowgate-api/src/test/java/com/vmware/flowgate/controller/FacilitySoftwareControllerTest.java

query facilities by types

---

ui/src/app/pages/facility/component/cmdb/cmdb-list/cmdb-list.component.ts
ui/src/app/pages/facility/component/dcim/dcim-list/dcim-list.component.ts
ui/src/app/pages/facility/component/dcim/dcim.service.ts

fix query facilities by page issue

---

ui/package-lock.json
ui/package.json

Signed-off-by: JinxiangWang <wjinxiang@vmware.com>

Fix Security Alert parsejson

---

flowgate-common/src/main/java/com/vmware/flowgate/common/model/ValueUnit.java
poweriq-worker/src/main/java/com/vmware/flowgate/poweriqworker/model/Outlet.java
poweriq-worker/src/main/java/com/vmware/flowgate/poweriqworker/model/OutletReading.java

Create data model for outlet

---

flowgate-api/src/main/java/com/vmware/flowgate/controller/AssetController.java
flowgate-api/src/main/java/com/vmware/flowgate/repository/AssetRepository.java

Change the asset source from one to many

---

flowgate-common/src/main/java/com/vmware/flowgate/common/FlowgateConstant.java

Add some constants for pdu

---

flowgate-common/src/main/java/com/vmware/flowgate/common/FlowgateConstant.java
flowgate-common/src/main/java/com/vmware/flowgate/common/model/PduInlet.java
flowgate-common/src/main/java/com/vmware/flowgate/common/model/PduOutlet.java
poweriq-worker/src/main/java/com/vmware/flowgate/poweriqworker/client/PowerIQAPIClient.java
poweriq-worker/src/main/java/com/vmware/flowgate/poweriqworker/model/Inlet.java
poweriq-worker/src/main/java/com/vmware/flowgate/poweriqworker/model/InletResult.java
poweriq-worker/src/main/java/com/vmware/flowgate/poweriqworker/model/Outlet.java
poweriq-worker/src/main/java/com/vmware/flowgate/poweriqworker/model/OutletReading.java
poweriq-worker/src/main/java/com/vmware/flowgate/poweriqworker/model/OutletsResult.java

Create data model for inlet and outlet

---

aggregator/src/main/java/com/vmware/flowgate/aggregator/scheduler/job/PowerIQJobDispatcher.java
flowgate-api/src/main/java/com/vmware/flowgate/controller/FacilitySoftwareController.java
flowgate-common/src/main/java/com/vmware/flowgate/common/FlowgateConstant.java
flowgate-common/src/main/java/com/vmware/flowgate/common/MountingSide.java
flowgate-common/src/main/java/com/vmware/flowgate/common/model/redis/message/impl/EventMessageUtil.java
poweriq-worker/src/main/java/com/vmware/flowgate/poweriqworker/client/PowerIQAPIClient.java
poweriq-worker/src/main/java/com/vmware/flowgate/poweriqworker/jobs/PowerIQService.java
poweriq-worker/src/test/java/com/vmware/flowgate/poweriqworker/jobtest/SyncPduAssetJobTest.java
poweriq-worker/src/test/java/com/vmware/flowgate/poweriqworker/jobtest/SyncSensorMetaDataJobTest.java

Add a job to sync pdu metadata in powerIQ_worker

---

flowgate-common/src/main/java/com/vmware/flowgate/common/model/Asset.java
flowgate-common/src/main/java/com/vmware/flowgate/common/model/Parent.java

Add a data model of parent

---

labsdb-worker/src/main/java/com/vmware/flowgate/labsdb/job/LabsdbService.java

Mdoify the logic of generate wire map info for server

---

poweriq-worker/src/main/java/com/vmware/flowgate/poweriqworker/jobs/PowerIQService.java

Add parent info for sensor asset

---

flowgate-common/src/main/java/com/vmware/flowgate/common/model/Asset.java

Add metricsformular for asset

---

flowgate-common/src/main/java/com/vmware/flowgate/common/MetricName.java
flowgate-common/src/main/java/com/vmware/flowgate/common/model/ValueUnit.java

Refactor the model of ValueUnit

---

flowgate-common/src/main/java/com/vmware/flowgate/common/model/redis/message/impl/EventMessageUtil.java

Add topic command for aggregating pdu from powerIq

---

common-restclient/src/main/java/com/vmware/flowgate/client/WormholeAPIClient.java

Add set endpoint method

---

poweriq-worker/src/main/java/com/vmware/flowgate/poweriqworker/client/PowerIQAPIClient.java
poweriq-worker/src/main/java/com/vmware/flowgate/poweriqworker/jobs/PowerIQService.java
poweriq-worker/src/test/java/com/vmware/flowgate/poweriqworker/jobtest/SyncRealTimeDataJobTest.java

Refactor the job of sync realtime data in powerIQ

---

nlyte-worker/src/main/java/com/vmware/flowgate/nlyteworker/scheduler/job/NlyteDataService.java

 Mpdify the logic of sync realtime data in Nlyte-worker

---

flowgate-common/src/main/java/com/vmware/flowgate/common/MetricName.java
poweriq-worker/src/main/java/com/vmware/flowgate/poweriqworker/jobs/PowerIQService.java
poweriq-worker/src/test/java/com/vmware/flowgate/poweriqworker/jobtest/SyncRealTimeDataJobTest.java

Record the current_load and power_load in powerIQ-worker

---

flowgate-common/src/main/java/com/vmware/flowgate/common/FlowgateConstant.java
flowgate-common/src/main/java/com/vmware/flowgate/common/MetricName.java

Add some metrics for pdu

---

aggregator/src/main/java/com/vmware/flowgate/aggregator/scheduler/job/AggregatorJobDispatcher.java
aggregator/src/main/java/com/vmware/flowgate/aggregator/scheduler/job/AggregatorService.java

Add job to aggregate and clean pdus which are from PowerIQ

---

common-restclient/src/main/java/com/vmware/flowgate/client/WormholeAPIClient.java
flowgate-api/src/main/java/com/vmware/flowgate/controller/AssetController.java

Modify the api of save assets

---

flowgate-common/src/main/java/com/vmware/flowgate/common/MetricName.java
flowgate-common/src/main/java/com/vmware/flowgate/common/model/Asset.java
flowgate-common/src/main/java/com/vmware/flowgate/common/model/SensorSetting.java
flowgate-common/src/main/java/com/vmware/flowgate/common/model/ServerSensorData.java

update data model

---

flowgate-api/src/main/java/com/vmware/flowgate/controller/AssetController.java
flowgate-api/src/main/java/com/vmware/flowgate/repository/SensorSettingRepository.java
flowgate-api/src/test/java/com/vmware/flowgate/controller/AssetControllerTest.java
flowgate-api/src/test/java/com/vmware/flowgate/controller/SensorSettingControllerTest.java

Refactor the api about serversensor type

---

nlyte-worker/src/main/java/com/vmware/flowgate/nlyteworker/scheduler/job/NlyteDataService.java
nlyte-worker/src/test/java/com/vmware/flowgate/nlyteworker/testjob/CleanDataJobTest.java
nlyte-worker/src/test/java/com/vmware/flowgate/nlyteworker/testjob/SycnRealTimeDataJobTest.java

Refactor the logic about metric name formular in nlyte-worker

---

common-restclient/src/main/java/com/vmware/flowgate/client/WormholeAPIClient.java
flowgate-api/src/main/java/com/vmware/flowgate/controller/AssetController.java

Revert the api of batch operation

---

flowgate-common/src/main/java/com/vmware/flowgate/common/FlowgateConstant.java

Update flowgate constant

---

poweriq-worker/src/main/java/com/vmware/flowgate/poweriqworker/jobs/PowerIQService.java
poweriq-worker/src/test/java/com/vmware/flowgate/poweriqworker/jobtest/SyncPduAssetJobTest.java
poweriq-worker/src/test/java/com/vmware/flowgate/poweriqworker/jobtest/SyncSensorMetaDataJobTest.java

Add logic to sync sensor realtime data for pdu

---

flowgate-common/src/main/java/com/vmware/flowgate/common/FlowgateConstant.java

Create a constant as rack unit prefix

---

aggregator/src/main/java/com/vmware/flowgate/aggregator/scheduler/job/AggregatorService.java

Refactor the function about sync sensor metrics for server

---

common-restclient/src/main/java/com/vmware/flowgate/client/WormholeAPIClient.java

Modify the method used to save asset in rest client

---

poweriq-worker/src/main/java/com/vmware/flowgate/poweriqworker/jobs/PowerIQService.java

Modify the logic about update metricsformular for pdu in powerIq-worker

---

vro-worker/src/main/java/com/vmware/flowgate/vroworker/scheduler/job/VROAsyncJob.java
vro-worker/src/main/java/com/vmware/flowgate/vroworker/vro/AlertClient.java
vro-worker/src/main/java/com/vmware/flowgate/vroworker/vro/MetricClient.java
vro-worker/src/main/java/com/vmware/flowgate/vroworker/vro/VROConsts.java

Modify the logic about ServerSensortype in vro-worker

---

flowgate-common/pom.xml

Upgrade the version of jackson because of the security alert

---

flowgate-common/src/main/java/com/vmware/flowgate/common/FlowgateConstant.java
flowgate-common/src/main/java/com/vmware/flowgate/common/MetricKeyName.java
flowgate-common/src/main/java/com/vmware/flowgate/common/MetricName.java
flowgate-common/src/main/java/com/vmware/flowgate/common/model/Asset.java
flowgate-common/src/main/java/com/vmware/flowgate/common/model/MetricData.java

Change name from ServerSensorData to MetricData

---

flowgate-api/src/main/java/com/vmware/flowgate/verifycert/VRopsAuth.java
vro-worker/src/main/java/com/vmware/flowgate/vroworker/vro/VROBase.java

Use token to communicate with vROPs.

---

poweriq-worker/src/main/java/com/vmware/flowgate/poweriqworker/jobs/PowerIQService.java

Filter absolute humidity sensor

---

flowgate-common/src/main/java/com/vmware/flowgate/common/MetricKeyName.java

Add metricNameKey for server

---

common-restclient/src/main/java/com/vmware/flowgate/client/WormholeAPIClient.java
flowgate-api/src/main/java/com/vmware/flowgate/controller/AssetController.java
flowgate-api/src/main/java/com/vmware/flowgate/repository/AssetRepository.java
flowgate-api/src/test/java/com/vmware/flowgate/controller/AssetControllerTest.java
vro-worker/src/main/java/com/vmware/flowgate/vroworker/scheduler/job/VROAsyncJob.java

Refactor logics about the serverSensorData in every worker

---

nlyte-worker/src/main/java/com/vmware/flowgate/nlyteworker/model/NlyteAsset.java
nlyte-worker/src/main/java/com/vmware/flowgate/nlyteworker/scheduler/job/common/HandleAssetUtil.java

Save totalCapacity and freecapacity for cabinet and network

---

flowgate-api/src/main/java/com/vmware/flowgate/controller/AssetController.java
flowgate-common/src/main/java/com/vmware/flowgate/common/MetricKeyName.java
flowgate-common/src/main/java/com/vmware/flowgate/common/MetricName.java

Create a new API to get realtime data for pdu

---

aggregator/src/main/java/com/vmware/flowgate/aggregator/scheduler/job/PowerIQJobDispatcher.java
common-restclient/src/main/java/com/vmware/flowgate/client/WormholeAPIClient.java
flowgate-api/src/main/java/com/vmware/flowgate/controller/FacilitySoftwareController.java
poweriq-worker/src/main/java/com/vmware/flowgate/poweriqworker/jobs/PowerIQService.java

Remove the job of sync pduID

---

flowgate-common/src/main/java/com/vmware/flowgate/common/FlowgateConstant.java
flowgate-common/src/main/java/com/vmware/flowgate/common/MetricKeyName.java

Add a new metric name key

---

flowgate-api/src/main/java/com/vmware/flowgate/controller/AssetController.java
flowgate-api/src/main/java/com/vmware/flowgate/service/AssetService.java

get server metrics data by id

---

flowgate-common/src/main/java/com/vmware/flowgate/common/model/SDDCSoftwareConfig.java

add a new type for sddc software config

---

aggregator/src/main/java/com/vmware/flowgate/aggregator/scheduler/job/AggregatorService.java
aggregator/src/test/java/com/vmware/flowgate/aggregator/MessageProcessingTest.java

Modify the function about sync sensor for server

---

flowgate-api/src/main/java/com/vmware/flowgate/controller/SDDCSoftwareController.java

Validate the type of sddc software config

---

ui/src/app/pages/sddcsoftware/component/vmware/vmware-config-list/vmware-config-list.component.html
ui/src/app/pages/sddcsoftware/component/vmware/vmware-config-list/vmware-config-list.component.ts

disabled all functions when the sddc type is VROPSMP

---

aggregator/src/main/java/com/vmware/flowgate/aggregator/scheduler/job/AggregatorService.java

Aggregate powerIQ's pdu to other system

---

aggregator/src/main/java/com/vmware/flowgate/aggregator/scheduler/job/AggregatorService.java

fix repeat add the same asset source bug

---

aggregator/src/main/java/com/vmware/flowgate/aggregator/scheduler/job/AggregatorService.java
flowgate-api/src/main/java/com/vmware/flowgate/service/AssetService.java
poweriq-worker/src/main/java/com/vmware/flowgate/poweriqworker/jobs/PowerIQService.java

fix null pointer error in the get realtime data api

---

flowgate-api/src/main/java/com/vmware/flowgate/service/AssetService.java

Modify the default time interval in apis of realtime data

---

aggregator/src/main/java/com/vmware/flowgate/aggregator/scheduler/job/AggregatorService.java

Modify the sources of asset

---

aggregator/src/main/java/com/vmware/flowgate/aggregator/scheduler/job/AggregatorService.java
aggregator/src/test/java/com/vmware/flowgate/aggregator/MessageProcessingTest.java

Remove pduids for server

---

flowgate-api/src/main/java/com/vmware/flowgate/controller/AssetController.java
flowgate-api/src/test/java/com/vmware/flowgate/controller/AssetControllerTest.java

Modify some test cases in assetControllerTest.class

---

flowgate-api/src/main/java/com/vmware/flowgate/controller/SDDCSoftwareController.java
vro-worker/src/test/java/com/vmware/flowgate/vroworker/TestVROPS.java

return null when the integration doesn't exsit.

Fix Null point exception

---

aggregator/src/main/java/com/vmware/flowgate/aggregator/scheduler/job/AggregatorService.java
flowgate-api/src/test/java/com/vmware/flowgate/controller/AssetControllerTest.java

Add testcase for the api of get pdu metrics data

---

ui/src/app/pages/nav/nav.component.html

Disable sensor setting page

---

flowgate-api/src/main/java/com/vmware/flowgate/controller/AssetController.java
flowgate-api/src/main/java/com/vmware/flowgate/service/AssetService.java
vro-worker/src/main/java/com/vmware/flowgate/vroworker/vro/AlertClient.java

Add some query options for realtime data api

---

flowgate-api/src/docs/asciidocs/api-guide.adoc
flowgate-api/src/test/java/com/vmware/flowgate/controller/AssetControllerTest.java

Modify api doc

---

make/aggregator/Dockerfile
make/flowgate-api/Dockerfile
make/infoblox-worker/Dockerfile
make/labsdb-worker/Dockerfile
make/management/Dockerfile
make/nlyte-worker/Dockerfile
make/poweriq-worker/Dockerfile
make/redis/Dockerfile
make/vc-worker/Dockerfile
make/vro-worker/Dockerfile

Update container before build

---

make/flowgate-api/Dockerfile
make/infoblox-worker/Dockerfile
make/labsdb-worker/Dockerfile
make/management/Dockerfile
make/nlyte-worker/Dockerfile
make/poweriq-worker/Dockerfile
make/redis/Dockerfile
make/vc-worker/Dockerfile
make/vro-worker/Dockerfile

Fix update software bug

---

make/aggregator/Dockerfile

Fix update software command

---

make/database/init.sh

Fix database sql bug

---

flowgate-api/src/main/java/com/vmware/flowgate/repository/SystemSummaryRepository.java
flowgate-api/src/main/java/com/vmware/flowgate/service/SummaryService.java

Modify the service of summary page

---

aggregator/src/main/java/com/vmware/flowgate/aggregator/scheduler/job/AggregatorJobDispatcher.java
poweriq-worker/src/main/java/com/vmware/flowgate/poweriqworker/jobs/PowerIQService.java

Trigger a job to aggregate pdu after finished to sync pdu from powerIQ

---

common-restclient/src/main/java/com/vmware/flowgate/client/WormholeAPIClient.java
flowgate-api/src/main/java/com/vmware/flowgate/controller/AssetController.java

Modify the api client of get server metrics data

---

vro-worker/src/main/java/com/vmware/flowgate/vroworker/scheduler/job/VROAsyncJob.java
vro-worker/src/main/java/com/vmware/flowgate/vroworker/vro/VROConsts.java

Push server metrics data to vrops

---

common-restclient/src/main/java/com/vmware/flowgate/client/WormholeAPIClient.java

Add a method in WormholeApiClient to get system summary data

---

aggregator/src/main/java/com/vmware/flowgate/aggregator/scheduler/job/AggregatorJobDispatcher.java
aggregator/src/main/java/com/vmware/flowgate/aggregator/scheduler/job/AggregatorService.java

Create a job to sync summary data in aggregator-worker

---

flowgate-api/src/main/java/com/vmware/flowgate/service/AssetService.java
flowgate-common/src/main/java/com/vmware/flowgate/common/MetricKeyName.java

Add power load and current load metrics for server

---

ui/src/app/pages/servermapping/servermapping.component.html
ui/src/app/pages/setting/setting.service.ts

Add VROPSMP as a search item for server mapping

---

flowgate-api/src/main/java/com/vmware/flowgate/controller/SystemSummaryController.java
flowgate-api/src/main/java/com/vmware/flowgate/service/SummaryService.java
flowgate-api/src/test/java/com/vmware/flowgate/controller/SystemSummaryTest.java
flowgate-common/src/main/java/com/vmware/flowgate/common/model/redis/message/impl/EventMessageUtil.java

Add cache for system summary data

---

nlyte-worker/src/main/java/com/vmware/flowgate/nlyteworker/scheduler/job/NlyteDataService.java
nlyte-worker/src/main/java/com/vmware/flowgate/nlyteworker/scheduler/job/common/HandleAssetUtil.java

Fix sync duplicate datas from the same nlyte

---

flowgate-api/src/test/java/com/vmware/flowgate/controller/SystemSummaryTest.java

Mock redis

---

nlyte-worker/src/main/java/com/vmware/flowgate/nlyteworker/restclient/NlyteAPIClient.java

Sync umounting info from nlyte for Network asset

---

poweriq-worker/src/main/java/com/vmware/flowgate/poweriqworker/jobs/PowerIQService.java
poweriq-worker/src/main/java/com/vmware/flowgate/poweriqworker/model/LocationInfo.java

Fix locationInfo Map is null

---

aggregator/src/main/java/com/vmware/flowgate/aggregator/scheduler/job/PowerIQJobDispatcher.java

Fix execount is 0 error

---

ui/src/app/pages/nav/nav.component.html

Fix unknown url

---

aggregator/src/main/java/com/vmware/flowgate/aggregator/scheduler/job/AggregatorService.java

Fix the assetName null pointer error

---

ui/src/app/pages/servermapping/servermapping.service.ts

Fix can't find vropsMp's serverMapping

---

ui/src/app/pages/sddcsoftware/component/vmware/vmware-config-list/vmware-config-list.component.html

Enable remove function for intergation with MP type

---

poweriq-worker/pom.xml
poweriq-worker/src/main/java/com/vmware/flowgate/poweriqworker/jobs/PowerIQService.java

Add a format check for rate value

---

aggregator/src/main/java/com/vmware/flowgate/aggregator/scheduler/job/AggregatorService.java

Add log info for aggregate PDU job

---

aggregator/src/main/java/com/vmware/flowgate/aggregator/scheduler/job/AggregatorService.java

Modify the job of aggregate and clean pdu

---

flowgate-common/src/main/java/com/vmware/flowgate/common/FlowgateConstant.java
flowgate-common/src/main/java/com/vmware/flowgate/common/model/CabinetU.java
nlyte-worker/src/main/java/com/vmware/flowgate/nlyteworker/model/CabinetU.java
nlyte-worker/src/main/java/com/vmware/flowgate/nlyteworker/model/NlyteAsset.java

Add data model for cabinetU

---

nlyte-worker/src/main/java/com/vmware/flowgate/nlyteworker/restclient/NlyteAPIClient.java
nlyte-worker/src/main/java/com/vmware/flowgate/nlyteworker/scheduler/job/common/HandleAssetUtil.java

Save cabinetUs info in nlyte-worker

---

aggregator/src/main/java/com/vmware/flowgate/aggregator/scheduler/job/AggregatorService.java

Fix assetName is null

---

poweriq-worker/src/main/java/com/vmware/flowgate/poweriqworker/jobs/PowerIQService.java

log pdu size

---

poweriq-worker/src/main/java/com/vmware/flowgate/poweriqworker/jobs/PowerIQService.java

Fix metrics value is mull

---

aggregator/src/main/java/com/vmware/flowgate/aggregator/scheduler/job/AggregatorService.java

Update metrics formula for pdu

---

poweriq-worker/src/main/java/com/vmware/flowgate/poweriqworker/jobs/PowerIQService.java

Query latest pdus when sync sensor asset

---

flowgate-common/src/main/java/com/vmware/flowgate/common/model/redis/message/impl/EventMessageUtil.java
poweriq-worker/src/main/java/com/vmware/flowgate/poweriqworker/jobs/PowerIQService.java

Add a job to sync sensor metric formula

---

poweriq-worker/src/main/java/com/vmware/flowgate/poweriqworker/jobs/PowerIQService.java
poweriq-worker/src/test/java/com/vmware/flowgate/poweriqworker/jobtest/SyncRealTimeDataJobTest.java

Enhance pdu load metrics

---

aggregator/src/main/java/com/vmware/flowgate/aggregator/scheduler/job/AggregatorService.java
aggregator/src/test/java/com/vmware/flowgate/aggregator/MessageProcessingTest.java
poweriq-worker/src/main/java/com/vmware/flowgate/poweriqworker/jobs/PowerIQService.java
poweriq-worker/src/test/java/com/vmware/flowgate/poweriqworker/jobtest/SyncSensorMetaDataJobTest.java

Fix format of position info WIP

---

aggregator/src/main/java/com/vmware/flowgate/aggregator/scheduler/job/AggregatorService.java
poweriq-worker/src/main/java/com/vmware/flowgate/poweriqworker/jobs/PowerIQService.java

Validate the sensor info map is null

---

flowgate-common/src/main/java/com/vmware/flowgate/common/MetricKeyName.java
poweriq-worker/src/main/java/com/vmware/flowgate/poweriqworker/jobs/PowerIQService.java

Modify metrics name

---

flowgate-common/src/main/java/com/vmware/flowgate/common/model/Asset.java
flowgate-common/src/main/java/com/vmware/flowgate/common/model/Tenant.java
nlyte-worker/src/main/java/com/vmware/flowgate/nlyteworker/model/CustomField.java
nlyte-worker/src/main/java/com/vmware/flowgate/nlyteworker/model/NlyteAsset.java
nlyte-worker/src/main/java/com/vmware/flowgate/nlyteworker/restclient/NlyteAPIClient.java
nlyte-worker/src/main/java/com/vmware/flowgate/nlyteworker/scheduler/job/NlyteDataService.java
nlyte-worker/src/main/java/com/vmware/flowgate/nlyteworker/scheduler/job/common/HandleAssetUtil.java

Add the tenant information for asset

---

flowgate-api/src/test/java/com/vmware/flowgate/controller/AssetControllerTest.java
flowgate-api/src/test/java/com/vmware/flowgate/controller/JobsControllerTest.java

Fix test cases for new field tenant.

---

ui/src/app/pages/servermapping/asset.module.ts
ui/src/app/pages/servermapping/servermapping.component.html
ui/src/app/pages/servermapping/servermapping.component.ts
ui/src/app/pages/servermapping/servermapping.service.ts

show mapped server asset

---

flowgate-api/src/main/java/com/vmware/flowgate/controller/AssetController.java

Fix assetSource bug

---

flowgate-api/src/docs/asciidocs/api-guide.adoc
flowgate-api/src/test/java/com/vmware/flowgate/controller/AssetControllerTest.java
nlyte-worker/src/main/java/com/vmware/flowgate/nlyteworker/scheduler/job/common/HandleAssetUtil.java

Sync column and row info for asset from nlyte

---

nlyte-worker/src/main/java/com/vmware/flowgate/nlyteworker/scheduler/job/common/HandleAssetUtil.java

Add the tenant information

---

poweriq-worker/src/main/java/com/vmware/flowgate/poweriqworker/jobs/PowerIQService.java

filter sensor source

---

flowgate-api/src/main/resources/application.properties
management/src/main/resources/application.properties

Increase the api timeout to 15 seconds.

---

ui/src/app/pages/servermapping/asset.module.ts
ui/src/app/pages/servermapping/servermapping.component.html
ui/src/app/pages/servermapping/servermapping.component.ts
ui/src/app/pages/servermapping/servermapping.service.ts

Mapping facility pages

---

flowgate-api/src/docs/asciidocs/api-guide.adoc
flowgate-api/src/test/java/com/vmware/flowgate/controller/AssetControllerTest.java

Test case for mapping facility api

---

flowgate-api/src/main/java/com/vmware/flowgate/controller/AssetController.java
ui/src/app/pages/servermapping/servermapping.component.html
ui/src/app/pages/servermapping/servermapping.component.ts

Remove total count of asset in search assets api

---

ui/src/app/pages/servermapping/servermapping.component.html
ui/src/app/pages/servermapping/servermapping.component.ts

Modify page number

---

flowgate-api/src/main/java/com/vmware/flowgate/service/AssetService.java

Add voltage metric for server

---

ui/src/app/pages/setting/host-name-and-ipmapping/host-name-and-ipmapping.module.ts

Create a data model for asset name and ip mapping

---

flowgate-api/src/docs/asciidocs/api-guide.adoc
flowgate-api/src/test/java/com/vmware/flowgate/controller/AssetControllerTest.java

Update the api document

---

flowgate-api/src/main/java/com/vmware/flowgate/service/AssetService.java

Remove the inlet metrics data in the api of get server realtime data

---

flowgate-api/src/test/java/com/vmware/flowgate/controller/AssetControllerTest.java

fix test error

---

flowgate-api/src/main/java/com/vmware/flowgate/service/AssetService.java

fix null pointer error

---

flowgate-api/src/main/java/com/vmware/flowgate/service/AssetService.java
poweriq-worker/src/main/java/com/vmware/flowgate/poweriqworker/jobs/PowerIQService.java

Modify the method of filter asset by source

---

aggregator/src/main/java/com/vmware/flowgate/aggregator/scheduler/job/AggregatorJobDispatcher.java

fix execute count error

---

ui/package-lock.json
ui/package.json

upgrade jquery

---

aggregator/pom.xml
common-restclient/pom.xml
flowgate-api/pom.xml
flowgate-common/pom.xml
infoblox-worker/pom.xml
labsdb-worker/pom.xml
management/pom.xml
nlyte-worker/pom.xml
poweriq-worker/pom.xml
vc-worker/pom.xml
vro-worker/pom.xml

Upgrade the version of jackson

---

aggregator/src/main/java/com/vmware/flowgate/aggregator/scheduler/job/AggregatorService.java

Fix a bug about generating pdu metrics fromula for server

---

.github/workflows/aggregator.yml
.github/workflows/flowgate-api.yml
.github/workflows/infoblox-worker.yml
.github/workflows/labsdb-worker.yml
.github/workflows/management.yml
.github/workflows/nlyte-worker.yml
.github/workflows/poweriq-worker.yml
.github/workflows/vc-worker.yml
.github/workflows/vro-worker.yml
aggregator/.travis.yml
aggregator/pom.xml
flowgate-api/.travis.yml
flowgate-api/pom.xml
infoblox-worker/.travis.yml
infoblox-worker/pom.xml
labsdb-worker/.travis.yml
labsdb-worker/pom.xml
management/.travis.yml
management/pom.xml
nlyte-worker/.travis.yml
nlyte-worker/pom.xml
poweriq-worker/.travis.yml
poweriq-worker/pom.xml
vc-worker/.travis.yml
vc-worker/pom.xml
vro-worker/.travis.yml
vro-worker/pom.xml

codecov feature

---

docs/compile_guide.md
docs/installation_guide.md

change version from 1.0 to 1.1

---

vro-worker/src/main/java/com/vmware/flowgate/vroworker/scheduler/job/VROAsyncJob.java

Modify the voltage's metricName

---

ui/src/app/pages/servermapping/servermapping.component.html
ui/src/app/pages/servermapping/servermapping.component.ts

Modify the serverMapping page

---

flowgate-api/pom.xml
vc-worker/pom.xml
vro-worker/pom.xml

Fix run jacoco when initialize the api issue

---

flowgate-api/src/docs/asciidocs/api-guide.adoc
flowgate-api/src/test/java/com/vmware/flowgate/controller/AssetControllerTest.java
flowgate-api/src/test/java/com/vmware/flowgate/controller/FacilitySoftwareControllerTest.java
flowgate-api/src/test/java/com/vmware/flowgate/controller/JobsControllerTest.java
flowgate-api/src/test/java/com/vmware/flowgate/controller/SDDCSoftwareControllerTest.java

Fix the api doc error

---

flowgate-api/pom.xml

upgrade the spring boot version

---

.github/workflows/aggregator.yml
.travis.yml
codecov.yml
flowgate-api/.travis.yml
infoblox-worker/.travis.yml
labsdb-worker/.travis.yml
management/.travis.yml
nlyte-worker/.travis.yml
poweriq-worker/.travis.yml
vc-worker/.travis.yml
vro-worker/.travis.yml

Fix code coverage issue with codecov

---

.travis.yml

specify base commit

---

ui/src/app/pages/servermapping/servermapping.component.ts

Fix serverMapping page display error

---

flowgate-common/src/main/java/com/vmware/flowgate/common/AssetCategory.java
flowgate-common/src/main/java/com/vmware/flowgate/common/FlowgateConstant.java
flowgate-common/src/main/java/com/vmware/flowgate/common/model/FlowgateChassisSlot.java
nlyte-worker/src/main/java/com/vmware/flowgate/nlyteworker/model/ChassisMountedAssetMap.java
nlyte-worker/src/main/java/com/vmware/flowgate/nlyteworker/model/ChassisSlot.java
nlyte-worker/src/main/java/com/vmware/flowgate/nlyteworker/model/Material.java
nlyte-worker/src/main/java/com/vmware/flowgate/nlyteworker/model/NlyteAsset.java

Modify data model for chassis

---

.github/workflows/aggregator.yml
.github/workflows/flowgate-api.yml
.github/workflows/infoblox-worker.yml
.github/workflows/labsdb-worker.yml
.github/workflows/management.yml
.github/workflows/nlyte-worker.yml
.github/workflows/poweriq-worker.yml
.github/workflows/vc-worker.yml
.github/workflows/vro-worker.yml
.travis.yml
codecov.yml

fix codecov yml

---

ui/package-lock.json

Fix security vulnerability

---

flowgate-common/src/main/java/com/vmware/flowgate/common/FlowgateConstant.java
nlyte-worker/src/main/java/com/vmware/flowgate/nlyteworker/restclient/NlyteAPIClient.java
nlyte-worker/src/main/java/com/vmware/flowgate/nlyteworker/scheduler/job/NlyteDataService.java
nlyte-worker/src/main/java/com/vmware/flowgate/nlyteworker/scheduler/job/common/HandleAssetUtil.java
nlyte-worker/src/test/java/com/vmware/flowgate/nlyteworker/testjob/SycnRealTimeDataJobTest.java

Sync chassis data from nlyte

---

nlyte-worker/src/main/java/com/vmware/flowgate/nlyteworker/scheduler/job/NlyteDataService.java

Check list is empty

---

flowgate-api/src/main/java/com/vmware/flowgate/service/AssetService.java
flowgate-api/src/test/java/com/vmware/flowgate/controller/AssetControllerTest.java
flowgate-common/src/main/java/com/vmware/flowgate/common/MetricKeyName.java

Get inlet pole metrics

---

nlyte-worker/src/main/java/com/vmware/flowgate/nlyteworker/scheduler/job/NlyteDataService.java
nlyte-worker/src/main/java/com/vmware/flowgate/nlyteworker/scheduler/job/common/HandleAssetUtil.java
nlyte-worker/src/test/java/com/vmware/flowgate/nlyteworker/testjob/SycnRealTimeDataJobTest.java

Update parent info for asset

---

flowgate-api/src/main/java/com/vmware/flowgate/controller/AssetController.java
flowgate-api/src/main/java/com/vmware/flowgate/exception/WormholeRequestException.java
flowgate-api/src/main/java/com/vmware/flowgate/security/service/PrepareSecurityMetadataSourceService.java
flowgate-api/src/main/java/com/vmware/flowgate/service/AssetService.java
flowgate-api/src/main/java/com/vmware/flowgate/util/PredefinedDataLoader.java

Fix Asset controller error

---

flowgate-api/src/main/java/com/vmware/flowgate/controller/AuthController.java
flowgate-api/src/main/java/com/vmware/flowgate/controller/FacilitySoftwareController.java
flowgate-api/src/main/java/com/vmware/flowgate/controller/SDDCSoftwareController.java
flowgate-api/src/main/java/com/vmware/flowgate/controller/SensorSettingController.java

Fix other controllers error

---

flowgate-api/src/test/java/com/vmware/flowgate/controller/AssetControllerTest.java
flowgate-api/src/test/java/com/vmware/flowgate/controller/AuthControllerTest.java
flowgate-api/src/test/java/com/vmware/flowgate/controller/FacilitySoftwareControllerTest.java
flowgate-api/src/test/java/com/vmware/flowgate/controller/SDDCSoftwareControllerTest.java
flowgate-api/src/test/java/com/vmware/flowgate/controller/SensorSettingControllerTest.java
flowgate-api/src/test/java/com/vmware/flowgate/controller/SystemSummaryTest.java

Fix API  test error

---

aggregator/pom.xml
common-restclient/pom.xml
flowgate-common/pom.xml
infoblox-worker/pom.xml
labsdb-worker/pom.xml
management/pom.xml
nlyte-worker/pom.xml
poweriq-worker/pom.xml
vc-worker/pom.xml
vro-worker/pom.xml
worker-jobs/pom.xml

Upgrade version of spring boot for all modules

---

aggregator/src/main/resources/application.properties
infoblox-worker/pom.xml
infoblox-worker/src/main/resources/application.properties
labsdb-worker/pom.xml
labsdb-worker/src/main/resources/application.properties
nlyte-worker/pom.xml
nlyte-worker/src/main/resources/application.properties
poweriq-worker/pom.xml
poweriq-worker/src/main/resources/application.properties
vc-worker/pom.xml
vc-worker/src/main/resources/application.properties
vro-worker/pom.xml
vro-worker/src/main/resources/application.properties

Use jedis client

---

flowgate-api/src/main/resources/application.properties

config the couchbase connect timeout

---

ui/src/app/pages/servermapping/servermapping.component.ts

Fix can't map back humidity sensor

---

flowgate-api/pom.xml
vro-worker/pom.xml
worker-jobs/pom.xml

Fix security vulnerabilities

---

aggregator/pom.xml

Upgrade quartz

---

.github/workflows/aggregator.yml
.github/workflows/flowgate-api.yml
.github/workflows/infoblox-worker.yml
.github/workflows/labsdb-worker.yml
.github/workflows/management.yml
.github/workflows/nlyte-worker.yml
.github/workflows/poweriq-worker.yml
.github/workflows/vc-worker.yml
.github/workflows/vro-worker.yml

trigger all workflow when pr

---

aggregator/pom.xml
common-restclient/pom.xml
flowgate-api/pom.xml
flowgate-common/pom.xml
infoblox-worker/pom.xml
labsdb-worker/pom.xml
management/pom.xml
nlyte-worker/pom.xml
poweriq-worker/pom.xml
vc-worker/pom.xml
vro-worker/pom.xml
worker-jobs/pom.xml

Upgrade flowgate version to 1.1.2

---

ui/.angular-cli.json
ui/package-lock.json
ui/package.json

Fix ui vulns

---

vc-worker/pom.xml

Upgrade the version of bcprov-jdk15on in vc-worker

---

make/redis/Dockerfile

update gosu version to latest

---

nlyte-worker/src/main/java/com/vmware/flowgate/nlyteworker/scheduler/job/NlyteDataService.java
poweriq-worker/src/main/java/com/vmware/flowgate/poweriqworker/jobs/PowerIQService.java

Modify the comment message

---

flowgate-api/src/main/java/com/vmware/flowgate/auth/InfobloxAuth.java
flowgate-api/src/main/java/com/vmware/flowgate/service/ServerValidationService.java
infoblox-worker/src/main/java/com/vmware/flowgate/infobloxworker/jobs/InfoBloxService.java
infoblox-worker/src/main/java/com/vmware/flowgate/infobloxworker/service/InfobloxClient.java

add infoblox validateFacilityServer , fix throw exception

---

flowgate-common/src/main/java/com/vmware/flowgate/common/model/AdapterJobCommand.java
flowgate-common/src/main/java/com/vmware/flowgate/common/model/AdapterType.java

Create data model for adapter type

---

nlyte-worker/src/main/java/com/vmware/flowgate/nlyteworker/scheduler/job/common/HandleAssetUtil.java
nlyte-worker/src/test/java/com/vmware/flowgate/nlyteworker/testjob/SycnRealTimeDataJobTest.java

Fix chassis slots is empty

---

ui/package-lock.json

Fix a security vulnerability about ui

---

flowgate-api/src/test/java/com/vmware/flowgate/controller/FacilitySoftwareControllerTest.java
flowgate-api/src/test/java/com/vmware/flowgate/controller/SDDCSoftwareControllerTest.java
flowgate-common/src/main/java/com/vmware/flowgate/common/model/FacilityAdapter.java
flowgate-common/src/main/java/com/vmware/flowgate/common/model/FacilitySoftwareConfig.java
flowgate-common/src/main/java/com/vmware/flowgate/common/model/SDDCSoftwareConfig.java

Update the data model of adapter

---

ui/src/app/pages/setting/component/asset-modules/asset.module.ts
ui/src/app/pages/setting/component/asset-modules/assetrealtimedataspec.module.ts
ui/src/app/pages/setting/component/asset-modules/assetstatus.module.ts

asset management ui module

---

ui/src/app/pages/nav/nav.component.html
ui/src/app/pages/nav/nav.component.ts
ui/src/app/pages/setting/component/asset-add/asset-add.component.html
ui/src/app/pages/setting/component/asset-add/asset-add.component.ts
ui/src/app/pages/setting/component/asset-edit/asset-edit.component.html
ui/src/app/pages/setting/component/asset-edit/asset-edit.component.scss
ui/src/app/pages/setting/component/asset-edit/asset-edit.component.ts
ui/src/app/pages/setting/component/asset-list/asset-list.component.html
ui/src/app/pages/setting/component/asset-list/asset-list.component.scss
ui/src/app/pages/setting/component/asset-list/asset-list.component.ts
ui/src/app/pages/setting/setting.module.ts
ui/src/app/pages/setting/setting.routing.ts
ui/src/app/pages/setting/setting.service.ts

add assetmanagement of setting

---

flowgate-api/src/docs/asciidocs/api-guide.adoc
flowgate-api/src/main/java/com/vmware/flowgate/controller/FacilityAdapterController.java
flowgate-api/src/main/java/com/vmware/flowgate/repository/FacilityAdapterRepository.java
flowgate-api/src/test/java/com/vmware/flowgate/controller/FacilityAdapterControllerTest.java

Create some APIs for adapter type

---

ui/src/app/pages/setting/component/asset-add/asset-add.component.html
ui/src/app/pages/setting/component/asset-edit/asset-edit.component.html
ui/src/app/pages/setting/component/asset-edit/asset-edit.component.ts
ui/src/app/pages/setting/component/asset-modules/asset.module.ts

edit page add Advance raw data

---

ui/package-lock.json
ui/package.json

Fix a security vulnerability

---

flowgate-api/src/main/java/com/vmware/flowgate/controller/FacilityAdapterController.java
flowgate-api/src/test/java/com/vmware/flowgate/controller/FacilityAdapterControllerTest.java

Fix test case

---

ui/src/app/pages/nav/nav.component.html
ui/src/app/pages/nav/nav.component.ts
ui/src/app/pages/setting/component/adaptertype/adapter-job-command.module.ts
ui/src/app/pages/setting/component/adaptertype/adaptertype-list/facility-adapter-list.component.html
ui/src/app/pages/setting/component/adaptertype/adaptertype-list/facility-adapter-list.component.ts
ui/src/app/pages/setting/component/adaptertype/facility-adapter.module.ts
ui/src/app/pages/setting/component/adaptertype/facility-adapter.service.ts
ui/src/app/pages/setting/setting.module.ts
ui/src/app/pages/setting/setting.routing.ts

UI pages for adapter management

---

flowgate-api/src/main/java/com/vmware/flowgate/controller/SDDCSoftwareController.java
flowgate-api/src/test/java/com/vmware/flowgate/controller/SDDCSoftwareControllerTest.java

delete servermapping before delete integretion

---

ui/src/app/pages/servermapping/servermapping.component.html

Support sort in HostMapping page

---

flowgate-api/src/main/java/com/vmware/flowgate/controller/FacilityAdapterController.java
flowgate-api/src/main/java/com/vmware/flowgate/repository/FacilitySoftwareConfigRepository.java
flowgate-api/src/main/java/com/vmware/flowgate/service/FacilityAdapterService.java
flowgate-api/src/test/java/com/vmware/flowgate/controller/AuthControllerTest.java
flowgate-api/src/test/java/com/vmware/flowgate/controller/FacilityAdapterControllerTest.java
flowgate-common/src/main/java/com/vmware/flowgate/common/FlowgateConstant.java
flowgate-common/src/main/java/com/vmware/flowgate/common/model/FacilityAdapter.java

Refactor the method of remove adapter

---

ui/src/app/pages/setting/component/adaptertype/adaptertype-list/facility-adapter-list.component.html
ui/src/app/pages/setting/component/adaptertype/adaptertype-list/facility-adapter-list.component.ts
ui/src/app/pages/setting/component/adaptertype/facility-adapter.module.ts

Update ui pages of adapter

---

ui/src/app/pages/facility/component/cmdb/cmdb-add/cmdb-add.component.html
ui/src/app/pages/facility/component/cmdb/cmdb-add/cmdb-add.component.ts
ui/src/app/pages/facility/component/cmdb/cmdb-edit/cmdb-edit.component.html
ui/src/app/pages/facility/component/cmdb/cmdb-edit/cmdb-edit.component.ts
ui/src/app/pages/facility/component/cmdb/cmdb-list/cmdb-list.component.ts
ui/src/app/pages/facility/component/dcim/dcim-add/dcim-add.component.html
ui/src/app/pages/facility/component/dcim/dcim-add/dcim-add.component.ts
ui/src/app/pages/facility/component/dcim/dcim-edit/dcim-edit.component.html
ui/src/app/pages/facility/component/dcim/dcim-edit/dcim-edit.component.ts
ui/src/app/pages/facility/component/dcim/dcim-list/dcim-list.component.ts
ui/src/app/pages/facility/component/dcim/dcim.service.ts
ui/src/app/pages/facility/facility.module.ts

Select a adapter type when create integrations

---

ui/src/app/pages/facility/component/cmdb/cmdb-add/cmdb-add.component.ts
ui/src/app/pages/nav/nav.component.html
ui/src/app/pages/setting/component/adaptertype/adaptertype-list/facility-adapter-list.component.html

By default the user name and password is required when create a cmdb integration

---

ui/package-lock.json

Fix security vulnerability about handlebars

---

aggregator/src/main/java/com/vmware/flowgate/aggregator/scheduler/job/CustomerAdapterJobDispatcher.java
aggregator/src/test/java/com/vmware/flowgate/aggregator/MessageProcessingTest.java
aggregator/src/test/resources/application.properties
common-restclient/src/main/java/com/vmware/flowgate/client/WormholeAPIClient.java
flowgate-common/src/main/java/com/vmware/flowgate/common/model/metadata/PredefinedSDDCJobs.java
flowgate-common/src/main/java/com/vmware/flowgate/common/model/redis/message/impl/EventMessageUtil.java

Trigger the customer adapters to execute jobs

---

adapter-sample/pom.xml
adapter-sample/src/main/java/com/vmware/flowgate/adapter/CustomerAdapterApplication.java
adapter-sample/src/main/java/com/vmware/flowgate/adapter/client/AdapterClient.java
adapter-sample/src/main/java/com/vmware/flowgate/adapter/job/AdapterJobService.java
adapter-sample/src/main/java/com/vmware/flowgate/adapter/redis/RedisConfig.java
adapter-sample/src/main/java/com/vmware/flowgate/adapter/redis/RedisMessageReceiver.java
adapter-sample/src/main/resources/META-INF/additional-spring-configuration-metadata.json
adapter-sample/src/main/resources/application.properties
adapter-sample/src/main/resources/logback-spring.xml
adapter-sample/src/test/java/com/vmware/flowgate/adapter/AdapterApplicationTest.java

Template project of customer adapter

---

aggregator/src/test/java/com/vmware/flowgate/aggregator/MessageProcessingTest.java
aggregator/src/test/resources/application.properties

Use annotation to replace properties file

---

ui/package-lock.json

Upgrade the version of http-proxy

---

aggregator/src/main/java/com/vmware/flowgate/aggregator/scheduler/job/CustomerAdapterJobDispatcher.java
aggregator/src/test/java/com/vmware/flowgate/aggregator/MessageProcessingTest.java

Remove local cache

---

adapter-sample/src/main/java/com/vmware/flowgate/adapter/client/AdapterClient.java
adapter-sample/src/main/java/com/vmware/flowgate/adapter/datamodel/MyDataModel1.java
adapter-sample/src/main/java/com/vmware/flowgate/adapter/job/AdapterJobService.java

Add some comments for adapter-sample

---

flowgate-api/src/main/java/com/vmware/flowgate/controller/AssetController.java
flowgate-api/src/test/java/com/vmware/flowgate/controller/AssetControllerTest.java

use the asset name to replace the asset id for servermapping

---

adapter-sample/src/main/java/com/vmware/flowgate/adapter/job/AdapterJobService.java

Add a method to check conncetion

---

docs/adapter_guide.md

Modify the adapter_guide

---

flowgate-api/src/test/java/com/vmware/flowgate/controller/AssetControllerTest.java

Fix test failing

---

ui/src/app/pages/facility/component/cmdb/cmdb-list/cmdb-list.component.html
ui/src/app/pages/facility/component/cmdb/cmdb-list/cmdb-list.component.ts
ui/src/app/pages/facility/component/dcim/dcim-list/dcim-list.component.html
ui/src/app/pages/facility/component/dcim/dcim-list/dcim-list.component.ts
ui/src/app/pages/sddcsoftware/component/vmware/vmware-config-list/vmware-config-list.component.html
ui/src/app/pages/sddcsoftware/component/vmware/vmware-config-list/vmware-config-list.component.ts
ui/src/app/pages/user/component/role-list/role-list.component.html
ui/src/app/pages/user/component/role-list/role-list.component.ts
ui/src/app/pages/user/component/user-list/user-list.component.html
ui/src/app/pages/user/component/user-list/user-list.component.ts

Add the loading step when query API in all list pages

---

ui/src/app/pages/nav/nav.component.html
ui/src/app/pages/servermapping/servermapping.component.html
ui/src/app/pages/servermapping/servermapping.component.ts
ui/src/app/pages/setting/component/adaptertype/adaptertype-list/facility-adapter-list.component.ts
ui/src/app/pages/setting/component/trigger-job/trigger-job.component.ts

Clear search result after the assets-list page is closed

---

ui/src/app/pages/setting/component/adaptertype/adaptertype-list/facility-adapter-list.component.html
ui/src/app/pages/setting/component/trigger-job/trigger-job.component.html

Fix the ui style in new adapter page

---

flowgate-api/src/test/java/com/vmware/flowgate/controller/AssetControllerTest.java
flowgate-api/src/test/java/com/vmware/flowgate/controller/FacilityAdapterControllerTest.java

Enhance the test cases of insert realtimedatas

---

flowgate-common/src/main/java/com/vmware/flowgate/common/FlowgateConstant.java
vc-worker/src/main/java/com/vmware/flowgate/vcworker/model/EsxiMetadata.java
vc-worker/src/main/java/com/vmware/flowgate/vcworker/model/HostInfo.java
vc-worker/src/main/java/com/vmware/flowgate/vcworker/model/HostNic.java
vc-worker/src/main/java/com/vmware/flowgate/vcworker/model/VCConstants.java

data model

---

vc-worker/src/main/java/com/vmware/flowgate/vcworker/model/HostRealtimeData.java

host realtime data model

---

aggregator/src/main/java/com/vmware/flowgate/aggregator/scheduler/job/VCenterJobDispatcher.java
aggregator/src/test/java/com/vmware/flowgate/aggregator/MessageProcessingTest.java
flowgate-common/src/main/java/com/vmware/flowgate/common/model/metadata/PredefinedSDDCJobs.java
flowgate-common/src/main/java/com/vmware/flowgate/common/model/redis/message/impl/EventMessageUtil.java

define vc cron job

---

ui/src/app/pages/facility/component/cmdb/cmdb-list/cmdb-list.component.ts
ui/src/app/pages/facility/component/dcim/dcim-list/dcim-list.component.ts
ui/src/app/pages/sddcsoftware/component/vmware/vmware-config-list/vmware-config-list.component.ts
ui/src/app/pages/setting/component/trigger-job/trigger-job.component.ts
ui/src/app/pages/user/component/user-add/user-add.component.ts
ui/src/app/pages/user/component/user-list/user-list.component.ts

Change the alter type

---

ui/src/app/pages/user/component/role-list/role-list.component.html
ui/src/app/pages/user/component/role-list/role-list.component.ts
ui/src/app/pages/user/component/user-add/user-add.component.html
ui/src/app/pages/user/component/user-add/user-add.component.ts
ui/src/app/pages/user/component/user-edit/user-edit.component.html
ui/src/app/pages/user/component/user-edit/user-edit.component.ts
ui/src/app/pages/user/component/user-list/user-list.component.ts
ui/src/app/pages/user/component/user-profile/user-profile.component.html
ui/src/app/pages/user/component/user-profile/user-profile.component.ts

Modify the pages include edit user and role page and user profile page

---

ui/package.json
ui/src/app/pages/sddcsoftware/component/vmware/vmware-config-add/vmware-config-add.component.html
ui/src/app/pages/sddcsoftware/component/vmware/vmware-config-add/vmware-config-add.component.ts
ui/src/app/pages/sddcsoftware/component/vmware/vmware-config-edit/vmware-config-edit.component.html
ui/src/app/pages/sddcsoftware/component/vmware/vmware-config-edit/vmware-config-edit.component.ts
ui/src/app/pages/sddcsoftware/component/vmware/vmware-config-list/vmware-config-list.component.ts
ui/src/app/pages/sddcsoftware/component/vmware/vmware.module.ts
ui/src/app/pages/sddcsoftware/sddcsoftware.module.ts
ui/src/app/pages/servermapping/mapping.module.ts
ui/src/app/pages/servermapping/servermapping.component.html
ui/src/app/pages/servermapping/servermapping.component.ts
ui/src/app/pages/servermapping/servermapping.module.ts
ui/src/app/pages/user/component/role-list/role-list.component.ts
ui/src/app/pages/user/component/user-add/user-add.component.ts
ui/src/app/pages/user/user.module.ts

Modify pages of SDDCSoftwareConfig

---

ui/src/app/pages/facility/component/cmdb/cmdb-add/cmdb-add.component.html
ui/src/app/pages/facility/component/cmdb/cmdb-add/cmdb-add.component.ts
ui/src/app/pages/facility/component/cmdb/cmdb-edit/cmdb-edit.component.html
ui/src/app/pages/facility/component/cmdb/cmdb-edit/cmdb-edit.component.ts
ui/src/app/pages/facility/component/dcim/dcim-add/dcim-add.component.html
ui/src/app/pages/facility/component/dcim/dcim-add/dcim-add.component.ts
ui/src/app/pages/facility/component/dcim/dcim-edit/dcim-edit.component.html
ui/src/app/pages/facility/component/dcim/dcim-edit/dcim-edit.component.ts
ui/src/app/pages/facility/component/dcim/dcim.module.ts
ui/src/app/pages/sddcsoftware/component/vmware/vmware-config-add/vmware-config-add.component.ts
ui/src/app/pages/sddcsoftware/component/vmware/vmware-config-edit/vmware-config-edit.component.ts
ui/src/app/pages/sddcsoftware/component/vmware/vmware.module.ts

Modify pages of Facility-software-config

---

ui/src/app/pages/servermapping/servermapping.component.html
ui/src/app/pages/servermapping/servermapping.component.ts

Modify pages of Server Mapping

---

ui/src/app/pages/facility/component/cmdb/cmdb-list/cmdb-list.component.html
ui/src/app/pages/facility/component/dcim/dcim-list/dcim-list.component.html
ui/src/app/pages/sddcsoftware/component/vmware/vmware-config-list/vmware-config-list.component.html
ui/src/app/pages/setting/component/adaptertype/adaptertype-list/facility-adapter-list.component.html
ui/src/app/pages/setting/component/adaptertype/adaptertype-list/facility-adapter-list.component.ts
ui/src/app/pages/setting/component/asset-list/asset-list.component.html
ui/src/app/pages/setting/component/sensorsetting-list/sensorsetting-list.component.html
ui/src/app/pages/setting/setting.module.ts
ui/src/app/pages/user/component/role-list/role-list.component.html
ui/src/app/pages/user/component/user-list/user-list.component.html

Modify pages of facility adapter

---

ui/src/app/pages/setting/component/asset-add/asset-add.component.html
ui/src/app/pages/setting/component/asset-edit/asset-edit.component.html
ui/src/app/pages/setting/component/trigger-job/trigger-job.component.html
ui/src/app/pages/setting/component/trigger-job/trigger-job.component.scss
ui/src/app/pages/setting/component/trigger-job/trigger-job.component.ts
ui/src/app/pages/setting/setting.module.ts
ui/src/app/pages/user/component/user-list/user-list.component.ts

Modify pages of AssetNameAndIPMaping

---

ui/src/app/pages/setting/component/trigger-job/sankey.chart.ts
ui/src/app/pages/setting/component/trigger-job/trigger-job.component.html
ui/src/app/pages/setting/component/trigger-job/trigger-job.component.ts
ui/src/app/pages/setting/setting.module.ts
ui/src/app/pages/setting/summary/summary.module.ts
ui/src/polyfills.ts
ui/src/tsconfig.json

Modify the pages of summary

---

ui/src/app/pages/setting/component/asset-add/asset-add.component.ts
ui/src/app/pages/setting/component/asset-modules/asset.module.ts
ui/src/app/pages/setting/component/trigger-job/sankey.chart.ts
ui/src/app/pages/setting/component/trigger-job/trigger-job.component.html
ui/src/app/pages/setting/setting.module.ts

Modify the pages of Setting

---

ui/src/app/pages/setting/component/asset-add/asset-add.component.html
ui/src/app/pages/setting/component/asset-add/asset-add.component.ts
ui/src/app/pages/setting/component/asset-list/asset-list.component.html
ui/src/app/pages/setting/component/asset-list/asset-list.component.ts
ui/src/app/pages/setting/setting.service.ts

Modify pages of asset

---

aggregator/src/main/java/com/vmware/flowgate/aggregator/scheduler/job/VCenterJobDispatcher.java
aggregator/src/test/java/com/vmware/flowgate/aggregator/MessageProcessingTest.java
vc-worker/src/main/java/com/vmware/flowgate/vcworker/client/VsphereClient.java
vc-worker/src/main/java/com/vmware/flowgate/vcworker/model/VCConstants.java
vc-worker/src/main/java/com/vmware/flowgate/vcworker/scheduler/job/VCDataService.java
vc-worker/src/test/java/com/vmware/flowgate/vcworker/VCDataServiceTest.java

logic of get host metadata from vc

---

flowgate-common/src/main/java/com/vmware/flowgate/common/model/FacilitySoftwareConfig.java
flowgate-common/src/main/java/com/vmware/flowgate/common/model/IntegrationStatus.java
flowgate-common/src/main/java/com/vmware/flowgate/common/model/SDDCSoftwareConfig.java
infoblox-worker/src/main/java/com/vmware/flowgate/infobloxworker/jobs/InfoBloxService.java
infoblox-worker/src/main/java/com/vmware/flowgate/infobloxworker/model/DiscoveredData.java
infoblox-worker/src/main/java/com/vmware/flowgate/infobloxworker/model/InfoBloxIPInfoResult.java
infoblox-worker/src/main/java/com/vmware/flowgate/infobloxworker/model/InfobloxHostRecordItem.java
infoblox-worker/src/main/java/com/vmware/flowgate/infobloxworker/model/InfobloxIpv4addressItem.java
infoblox-worker/src/main/java/com/vmware/flowgate/infobloxworker/model/JsonResultForQueryHostNames.java
infoblox-worker/src/main/java/com/vmware/flowgate/infobloxworker/model/JsonResultForQueryHostRecord.java
infoblox-worker/src/main/java/com/vmware/flowgate/infobloxworker/service/InfobloxClient.java
infoblox-worker/src/test/java/com/vmware/flowgate/infobloxworker/controller/InfobloxClientTest.java
infoblox-worker/src/test/java/com/vmware/flowgate/infobloxworker/controller/InfobloxServiceTest.java

Add record host wapi

---

infoblox-worker/src/main/java/com/vmware/flowgate/infobloxworker/jobs/InfoBloxService.java

Rollback setServiceKey

---

flowgate-api/src/docs/asciidocs/api-guide.adoc
flowgate-api/src/main/java/com/vmware/flowgate/controller/AssetController.java
flowgate-api/src/main/java/com/vmware/flowgate/repository/AssetRepository.java
flowgate-api/src/test/java/com/vmware/flowgate/controller/AssetControllerTest.java

Modify the api of get assets by source

---

ui/src/app/pages/facility/component/cmdb/cmdb-list/cmdb-list.component.ts
ui/src/app/pages/facility/component/dcim/dcim-list/dcim-list.component.ts
ui/src/app/pages/setting/component/sensorsetting-list/sensorsetting-list.component.ts
ui/src/app/pages/user/component/role-list/role-list.component.html
ui/src/app/pages/user/component/role-list/role-list.component.ts
ui/src/app/pages/user/component/user-list/user-list.component.html
ui/src/app/pages/user/component/user-list/user-list.component.ts

Modify pages of role management

---

make/maven-docker-build/buildui.sh

Modify the version of angular-cli in buildui.sh

---

ui/src/app/pages/setting/component/asset-edit/asset-edit.component.html
ui/src/app/pages/setting/component/asset-edit/asset-edit.component.ts
ui/src/app/pages/setting/component/asset-modules/asset-temp.module.ts

uodate edit asset page

---

ui/src/app/pages/setting/component/asset-edit/asset-edit.component.html
ui/src/app/pages/setting/component/asset-edit/asset-edit.component.ts
ui/src/app/pages/setting/component/asset-modules/asset-temp.module.ts

update edit asset page

---

make/maven-docker-build/DockerfileUI
make/maven-docker-build/buildui.sh

Modify the buildui.sh

---

ui/src/app/pages/auth/AuthenticationInterceptor.ts
ui/src/app/pages/sddcsoftware/component/vmware/vmware-config-list/vmware-config-list.component.ts
ui/src/app/pages/servermapping/servermapping.component.html
ui/src/app/pages/servermapping/servermapping.component.ts
ui/src/app/pages/setting/component/trigger-job/trigger-job.component.ts
ui/src/app/pages/user-login/user-login.component.ts

Fix can't map server asset error

---

ui/src/app/pages/user/component/role-list/role-list.component.html
ui/src/app/pages/user/component/role-list/role-list.component.ts
ui/src/app/pages/user/component/user-add/user-add.component.ts
ui/src/app/pages/user/component/user-list/user-list.component.ts

Add the loading action when click next button

---

flowgate-api/src/main/java/com/vmware/flowgate/controller/AuthController.java
flowgate-api/src/test/java/com/vmware/flowgate/controller/AuthControllerTest.java

Add a validation for modify role name

---

ui/src/app/pages/auth/AuthenticationInterceptor.ts

Modify the http interceptor in ui

---

ui/src/app/pages/facility/component/cmdb/cmdb-edit/cmdb-edit.component.ts
ui/src/app/pages/facility/component/cmdb/cmdb-list/cmdb-list.component.html
ui/src/app/pages/facility/component/cmdb/cmdb-list/cmdb-list.component.ts
ui/src/app/pages/facility/component/dcim/dcim-list/dcim-list.component.html
ui/src/app/pages/facility/component/dcim/dcim-list/dcim-list.component.ts
ui/src/app/pages/setting/component/adaptertype/adaptertype-list/facility-adapter-list.component.html
ui/src/app/pages/setting/component/adaptertype/adaptertype-list/facility-adapter-list.component.ts
ui/src/app/pages/user/component/user-list/user-list.component.html

Fix angrlar ui Bug

---

ui/src/app/pages/setting/component/trigger-job/sankey.chart.ts

fix topology bug.

---

ui/src/app/pages/facility/component/cmdb/cmdb-edit/cmdb-edit.component.ts

fix infoblox page advance Setting Invalid modification

---

ui/src/app/pages/facility/component/cmdb/cmdb-edit/cmdb-edit.component.html
ui/src/app/pages/facility/component/cmdb/cmdb-edit/cmdb-edit.component.ts
ui/src/app/pages/facility/component/dcim/dcim-edit/dcim-edit.component.html
ui/src/app/pages/facility/component/dcim/dcim-edit/dcim-edit.component.ts

Data center facility page server field modification disabled

---

ui/src/app/pages/setting/component/trigger-job/trigger-job.component.ts

1. when api disconnect , error message cannot display.

fix synv data bug.

---

ui/src/app/pages/setting/component/asset-add/asset-add.component.html
ui/src/app/pages/setting/component/asset-add/asset-add.component.scss
ui/src/app/pages/setting/component/asset-add/asset-add.component.ts
ui/src/app/pages/setting/component/asset-edit/asset-edit.component.html
ui/src/app/pages/setting/component/asset-edit/asset-edit.component.scss
ui/src/app/pages/setting/component/asset-edit/asset-edit.component.ts
ui/src/app/pages/setting/component/asset-list/asset-list.component.ts
ui/src/app/pages/setting/component/asset-modules/asset-temp.module.ts

1. fix add and edit asset page, in some cases the submit button cannot be activated.
2. fix edit asset, advance setting cannot be linked with normal mode.
3. fix delete, cannot refresh list page.
4. add advance css, optimize the UI .

fix asset management bug.

---

ui/src/app/pages/setting/component/trigger-job/trigger-job.component.html
ui/src/app/pages/setting/component/trigger-job/trigger-job.component.ts

1. when api disconnect, error message connot display.

fix unmapping server page.

---

ui/src/app/pages/setting/component/trigger-job/trigger-job.component.html
ui/src/app/pages/setting/component/trigger-job/trigger-job.component.ts

1. After the first failed addition, click the add button again, the error message is not cleared.

fix AssetName and IP Mapping Add button.

---

README.md

testcodecov

---

codecov.yml

make base commit

---

codecov.yml

rollback codecov yml file

---

ui/src/app/pages/facility/component/cmdb/cmdb-add/cmdb-add.component.ts
ui/src/app/pages/facility/component/cmdb/cmdb-edit/cmdb-edit.component.ts
ui/src/app/pages/facility/component/dcim/dcim-add/dcim-add.component.ts
ui/src/app/pages/facility/component/dcim/dcim-edit/dcim-edit.component.ts

Fix the data reversed issue in edit facility integration page

---

flowgate-api/src/main/java/com/vmware/flowgate/service/ServerValidationService.java
flowgate-api/src/main/java/com/vmware/flowgate/verifycert/VRopsAuth.java
vro-worker/src/main/java/com/vmware/flowgate/vroworker/vro/VROBase.java

Modify the error message of server validation

---

flowgate-common/src/main/java/com/vmware/flowgate/common/FlowgateConstant.java
flowgate-common/src/main/java/com/vmware/flowgate/common/MetricName.java
flowgate-common/src/main/java/com/vmware/flowgate/common/RealtimeDataUnit.java
vc-worker/src/main/java/com/vmware/flowgate/vcworker/client/VsphereClient.java
vc-worker/src/main/java/com/vmware/flowgate/vcworker/model/VCConstants.java
vc-worker/src/main/java/com/vmware/flowgate/vcworker/scheduler/job/VCDataService.java
vc-worker/src/test/java/com/vmware/flowgate/vcworker/VCDataServiceTest.java

query vc realtime data

---

flowgate-api/src/main/java/com/vmware/flowgate/controller/FacilitySoftwareController.java
ui/src/app/pages/facility/component/cmdb/cmdb-edit/cmdb-edit.component.ts
ui/src/app/pages/facility/component/dcim/dcim-edit/dcim-edit.component.ts

Fix cmdb and dcim page modification error

---

codecov.yml

remove unuseful code

---

ui/src/app/pages/facility/component/cmdb/cmdb-add/cmdb-add.component.ts
ui/src/app/pages/facility/component/cmdb/cmdb-edit/cmdb-edit.component.ts
ui/src/app/pages/facility/component/dcim/dcim-add/dcim-add.component.ts
ui/src/app/pages/facility/component/dcim/dcim-edit/dcim-edit.component.ts

Use error code to instead of error message

---

flowgate-api/src/main/java/com/vmware/flowgate/controller/AssetController.java
flowgate-api/src/main/java/com/vmware/flowgate/service/AssetService.java
flowgate-api/src/test/java/com/vmware/flowgate/controller/AssetControllerTest.java

1.Add unified api, call according to type
2.Increase the method of acquiring realtimedata for Sensors

Enhanced realtimedata

---

flowgate-api/src/main/resources/logback-spring.xml
infoblox-worker/src/main/resources/logback-spring.xml

Remove the levelFilter for info-log

---

flowgate-common/src/main/java/com/vmware/flowgate/common/MetricName.java

Host metrics

---

flowgate-common/src/main/java/com/vmware/flowgate/common/model/FacilitySoftwareConfig.java
flowgate-common/src/main/java/com/vmware/flowgate/common/model/redis/message/impl/EventMessageUtil.java
openmanage/pom.xml
openmanage/src/main/java/com/vmware/flowgate/openmanage/OpenManageApplication.java
openmanage/src/main/java/com/vmware/flowgate/openmanage/client/OpenManageAPIClient.java
openmanage/src/main/java/com/vmware/flowgate/openmanage/config/ServiceKeyConfig.java
openmanage/src/main/java/com/vmware/flowgate/openmanage/datamodel/Chassis.java
openmanage/src/main/java/com/vmware/flowgate/openmanage/datamodel/ChassisSpecificData.java
openmanage/src/main/java/com/vmware/flowgate/openmanage/datamodel/ChassissResult.java
openmanage/src/main/java/com/vmware/flowgate/openmanage/datamodel/CommonObject.java
openmanage/src/main/java/com/vmware/flowgate/openmanage/datamodel/Device.java
openmanage/src/main/java/com/vmware/flowgate/openmanage/datamodel/DeviceManagement.java
openmanage/src/main/java/com/vmware/flowgate/openmanage/datamodel/ManagementProfile.java
openmanage/src/main/java/com/vmware/flowgate/openmanage/datamodel/Server.java
openmanage/src/main/java/com/vmware/flowgate/openmanage/datamodel/ServerSpecificData.java
openmanage/src/main/java/com/vmware/flowgate/openmanage/datamodel/ServersResult.java
openmanage/src/main/java/com/vmware/flowgate/openmanage/datamodel/SlotConfiguration.java
openmanage/src/main/java/com/vmware/flowgate/openmanage/job/OpenManageJobService.java
openmanage/src/main/java/com/vmware/flowgate/openmanage/redis/RedisConfig.java
openmanage/src/main/java/com/vmware/flowgate/openmanage/redis/RedisMessageReceiver.java
openmanage/src/main/resources/META-INF/additional-spring-configuration-metadata.json
openmanage/src/main/resources/application.properties
openmanage/src/main/resources/logback-spring.xml
openmanage/src/test/java/com/vmware/flowgate/openmanage/OpenManageApplicationTest.java

init openmanage-worker project

---

ui/src/app/pages/setting/component/asset-add/asset-add.component.html
ui/src/app/pages/setting/component/asset-edit/asset-edit.component.html

Add validation on Asset add/edit page

---

flowgate-api/src/main/java/com/vmware/flowgate/service/AssetService.java
flowgate-api/src/test/java/com/vmware/flowgate/controller/AssetControllerTest.java

Filter the outlet metrics value by server used

---

openmanage/pom.xml
openmanage/src/main/java/com/vmware/flowgate/openmanage/client/OpenManageAPIClient.java
openmanage/src/main/java/com/vmware/flowgate/openmanage/datamodel/DeviceType.java
openmanage/src/main/java/com/vmware/flowgate/openmanage/datamodel/DevicesResult.java
openmanage/src/main/java/com/vmware/flowgate/openmanage/datamodel/Server.java
openmanage/src/main/java/com/vmware/flowgate/openmanage/job/OpenManageJobService.java
openmanage/src/main/java/com/vmware/flowgate/openmanage/redis/RedisConfig.java

Add some methods to get servers and check connection

---

vc-worker/src/main/java/com/vmware/flowgate/vcworker/scheduler/job/VCDataService.java
vc-worker/src/test/java/com/vmware/flowgate/vcworker/VCDataServiceTest.java

Fix not generate host metrics formulars

---

ui/package-lock.json
ui/package.json

Fix a ui security vulnerability about socket.io

---

.github/workflows/openmanage.yml
codecov.yml
openmanage/src/main/java/com/vmware/flowgate/openmanage/job/OpenManageJobService.java

codecov script for openmange

---

flowgate-api/src/main/java/com/vmware/flowgate/service/AssetService.java
flowgate-api/src/test/java/com/vmware/flowgate/controller/AssetControllerTest.java
flowgate-common/src/main/java/com/vmware/flowgate/common/FlowgateConstant.java
flowgate-common/src/main/java/com/vmware/flowgate/common/MetricName.java
vc-worker/src/main/java/com/vmware/flowgate/vcworker/scheduler/job/VCDataService.java

Add hostMetric in getRealtimedata API

---

flowgate-common/src/main/java/com/vmware/flowgate/common/FlowgatePowerState.java
flowgate-common/src/main/java/com/vmware/flowgate/common/model/redis/message/EventType.java
flowgate-common/src/main/java/com/vmware/flowgate/common/model/redis/message/impl/EventMessageUtil.java

New data model for power state

---

flowgate-api/src/main/java/com/vmware/flowgate/auth/OpenManageAuth.java
flowgate-api/src/main/java/com/vmware/flowgate/controller/FacilitySoftwareController.java
flowgate-api/src/main/java/com/vmware/flowgate/service/ServerValidationService.java
flowgate-api/src/test/java/com/vmware/flowgate/controller/FacilitySoftwareControllerTest.java
flowgate-common/src/main/java/com/vmware/flowgate/common/model/redis/message/EventType.java
ui/src/app/pages/facility/component/dcim/dcim-add/dcim-add.component.ts
ui/src/app/pages/facility/component/dcim/dcim-edit/dcim-edit.component.ts
ui/src/app/pages/facility/component/dcim/dcim-list/dcim-list.component.ts

Add some methods to valid and create a openManage integration

---

openmanage/src/main/java/com/vmware/flowgate/openmanage/client/OpenManageAPIClient.java
openmanage/src/main/java/com/vmware/flowgate/openmanage/datamodel/DeviceMetric.java
openmanage/src/main/java/com/vmware/flowgate/openmanage/datamodel/DeviceMetricsResult.java
openmanage/src/main/java/com/vmware/flowgate/openmanage/datamodel/DevicePower.java
openmanage/src/main/java/com/vmware/flowgate/openmanage/datamodel/DeviceTemperature.java

Create data model of metrics for openmanage

---

flowgate-common/src/main/java/com/vmware/flowgate/common/FlowgateConstant.java
openmanage/src/main/java/com/vmware/flowgate/openmanage/client/OpenManageAPIClient.java
openmanage/src/main/java/com/vmware/flowgate/openmanage/job/OpenManageJobService.java
openmanage/src/test/java/com/vmware/flowgate/openmanage/jobtest/OpenManageJobTest.java

Sync metadata job

---

flowgate-api/src/main/java/com/vmware/flowgate/controller/AssetController.java

Fix the assetSource field is null

---

openmanage/src/main/java/com/vmware/flowgate/openmanage/client/OpenManageAPIClient.java
openmanage/src/main/java/com/vmware/flowgate/openmanage/datamodel/Duration.java
openmanage/src/main/java/com/vmware/flowgate/openmanage/datamodel/EntityType.java
openmanage/src/main/java/com/vmware/flowgate/openmanage/datamodel/MetricType.java
openmanage/src/main/java/com/vmware/flowgate/openmanage/datamodel/Plugin.java
openmanage/src/main/java/com/vmware/flowgate/openmanage/datamodel/SortOrder.java

Data model for openmanage-plugin

---

flowgate-api/src/docs/asciidocs/api-guide.adoc
flowgate-api/src/main/java/com/vmware/flowgate/controller/AssetController.java
flowgate-api/src/main/java/com/vmware/flowgate/service/AssetService.java
flowgate-api/src/test/java/com/vmware/flowgate/controller/AssetControllerTest.java

Enhance Flowgate Api Doc

---

flowgate-common/src/main/java/com/vmware/flowgate/common/MetricName.java
openmanage/src/main/java/com/vmware/flowgate/openmanage/client/OpenManageAPIClient.java

Create some methods to get metrics data from opemmanage

---

openmanage/src/main/java/com/vmware/flowgate/openmanage/datamodel/PowerDisplayUnit.java
openmanage/src/main/java/com/vmware/flowgate/openmanage/datamodel/PowerManageMetricsRequestBody.java
openmanage/src/main/java/com/vmware/flowgate/openmanage/datamodel/PowerSetting.java
openmanage/src/main/java/com/vmware/flowgate/openmanage/datamodel/PowerSettingType.java
openmanage/src/main/java/com/vmware/flowgate/openmanage/datamodel/TemperatureDisplayUnit.java

Create data model for power setting

---

ui/src/app/pages/user-login/user-login.component.html

Hide remember me checkbox

---

aggregator/src/main/java/com/vmware/flowgate/aggregator/scheduler/job/AggregatorService.java
aggregator/src/test/java/com/vmware/flowgate/aggregator/MessageProcessingTest.java
flowgate-api/src/main/java/com/vmware/flowgate/service/AssetService.java
flowgate-api/src/test/java/com/vmware/flowgate/controller/AssetControllerTest.java

Modify the flowgate-api and aggregator

---

nlyte-worker/src/main/java/com/vmware/flowgate/nlyteworker/scheduler/job/NlyteDataService.java
nlyte-worker/src/test/java/com/vmware/flowgate/nlyteworker/testjob/CleanDataJobTest.java
nlyte-worker/src/test/java/com/vmware/flowgate/nlyteworker/testjob/SycnRealTimeDataJobTest.java

Modify asset formula nlyte-worker

---

poweriq-worker/src/main/java/com/vmware/flowgate/poweriqworker/jobs/PowerIQService.java
poweriq-worker/src/test/java/com/vmware/flowgate/poweriqworker/jobtest/SyncPduAssetJobTest.java
poweriq-worker/src/test/java/com/vmware/flowgate/poweriqworker/jobtest/SyncSensorMetaDataJobTest.java

Modify asset formula powerIQ-worker

---

ui/src/app/pages/servermapping/asset.module.ts
ui/src/app/pages/servermapping/servermapping.component.ts

Fix metrics formula issue for ui

---

vc-worker/src/main/java/com/vmware/flowgate/vcworker/scheduler/job/VCDataService.java
vc-worker/src/test/java/com/vmware/flowgate/vcworker/VCDataServiceTest.java

Modify asset formula vc-worker

---

nlyte-worker/src/main/java/com/vmware/flowgate/nlyteworker/scheduler/job/NlyteDataService.java

Modify the error log

---

flowgate-common/src/main/java/com/vmware/flowgate/common/model/Asset.java

Add serialization and deserialization method for metric formula  in Asset.class

Add serialization and deserialization method for metric formula 

---

flowgate-common/src/main/java/com/vmware/flowgate/common/model/Asset.java

Fix the asset method permission modifier

---

nlyte-worker/src/main/java/com/vmware/flowgate/nlyteworker/scheduler/job/NlyteDataService.java
poweriq-worker/src/main/java/com/vmware/flowgate/poweriqworker/jobs/PowerIQService.java
vc-worker/src/main/java/com/vmware/flowgate/vcworker/scheduler/job/VCDataService.java

Refactor asset formular on poweriq-worker, vc-worker, nlyte-worker

---

aggregator/src/main/java/com/vmware/flowgate/aggregator/scheduler/job/AggregatorService.java
flowgate-api/src/main/java/com/vmware/flowgate/service/AssetService.java

Format the metric formula

---

flowgate-api/src/main/java/com/vmware/flowgate/service/AssetService.java
flowgate-api/src/test/java/com/vmware/flowgate/controller/AssetControllerTest.java

Modify getServerMetricsData to obtain MetricsData according to the formula

---

aggregator/src/main/java/com/vmware/flowgate/aggregator/scheduler/job/AggregatorService.java
aggregator/src/test/java/com/vmware/flowgate/aggregator/MessageProcessingTest.java
flowgate-api/src/main/java/com/vmware/flowgate/service/AssetService.java
flowgate-api/src/test/java/com/vmware/flowgate/controller/AssetControllerTest.java
flowgate-common/src/main/java/com/vmware/flowgate/common/model/Asset.java
nlyte-worker/src/main/java/com/vmware/flowgate/nlyteworker/scheduler/job/NlyteDataService.java
nlyte-worker/src/test/java/com/vmware/flowgate/nlyteworker/testjob/CleanDataJobTest.java
nlyte-worker/src/test/java/com/vmware/flowgate/nlyteworker/testjob/SycnRealTimeDataJobTest.java
poweriq-worker/src/main/java/com/vmware/flowgate/poweriqworker/jobs/PowerIQService.java
poweriq-worker/src/test/java/com/vmware/flowgate/poweriqworker/jobtest/SyncPduAssetJobTest.java
poweriq-worker/src/test/java/com/vmware/flowgate/poweriqworker/jobtest/SyncSensorMetaDataJobTest.java
vc-worker/src/main/java/com/vmware/flowgate/vcworker/scheduler/job/VCDataService.java
vc-worker/src/test/java/com/vmware/flowgate/vcworker/VCDataServiceTest.java

Revert to metricformular

---

ui/src/app/pages/servermapping/asset.module.ts
ui/src/app/pages/servermapping/servermapping.component.ts

Update asset data model for ui

---

flowgate-common/src/main/java/com/vmware/flowgate/common/MetricName.java
flowgate-common/src/main/java/com/vmware/flowgate/common/model/ValueUnit.java
flowgate-common/src/main/java/com/vmware/flowgate/common/utils/WormholeDateFormat.java
openmanage/src/main/java/com/vmware/flowgate/openmanage/client/OpenManageAPIClient.java
openmanage/src/main/java/com/vmware/flowgate/openmanage/datamodel/CommonResult.java
openmanage/src/main/java/com/vmware/flowgate/openmanage/datamodel/PowerSettingType.java
openmanage/src/main/java/com/vmware/flowgate/openmanage/job/OpenManageJobService.java
openmanage/src/main/resources/application.properties
openmanage/src/test/java/com/vmware/flowgate/openmanage/jobtest/OpenManageJobTest.java

Sync metrics data job

---

aggregator/src/main/java/com/vmware/flowgate/aggregator/scheduler/job/OpenmanageJobDispatcher.java
aggregator/src/test/java/com/vmware/flowgate/aggregator/MessageProcessingTest.java
flowgate-common/src/main/java/com/vmware/flowgate/common/model/metadata/PredefinedSDDCJobs.java
flowgate-common/src/main/java/com/vmware/flowgate/common/model/redis/message/impl/EventMessageUtil.java

Cron job for openmanage

---

aggregator/pom.xml
common-restclient/pom.xml
flowgate-api/pom.xml
flowgate-common/pom.xml
infoblox-worker/pom.xml
labsdb-worker/pom.xml
management/pom.xml
nlyte-worker/pom.xml
openmanage/pom.xml
poweriq-worker/pom.xml
vc-worker/pom.xml
vro-worker/pom.xml
worker-jobs/pom.xml

Update the flowgate version

---

ui/package-lock.json

Fix ui vulnerability

---

openmanage/src/main/resources/application.properties
poweriq-worker/src/main/java/com/vmware/flowgate/poweriqworker/jobs/PowerIQService.java

Change unit format from RealtimeDataUnit to MetricUnit

---

flowgate-common/src/main/java/com/vmware/flowgate/common/model/ValueUnit.java
vc-worker/src/main/java/com/vmware/flowgate/vcworker/model/VCConstants.java
vc-worker/src/main/java/com/vmware/flowgate/vcworker/scheduler/job/VCDataService.java
vc-worker/src/test/java/com/vmware/flowgate/vcworker/VCDataServiceTest.java

Get power related metrics from vc and save

---

contrib/ar4dcops/README

Initialize the ar4dcops project

---

flowgate-api/pom.xml
poweriq-worker/pom.xml
poweriq-worker/src/main/java/com/vmware/flowgate/poweriqworker/client/PowerIQAPIClient.java

Fix tomcat CVE-2021-25329

---

make/build.sh
make/flowgate_init.sh
make/maven-docker-build/build.sh
make/maven-docker-build/docker-compose.build.images.yml
make/maven-docker-build/docker-compose.run.images.yml
make/openmanage/Dockerfile
make/openmanage/start.sh

Modify build script for openmanage

---

flowgate-api/src/main/java/com/vmware/flowgate/service/AssetService.java
flowgate-api/src/test/java/com/vmware/flowgate/controller/AssetControllerTest.java
flowgate-common/src/main/java/com/vmware/flowgate/common/model/MetricData.java
flowgate-common/src/main/java/com/vmware/flowgate/common/model/ValueUnit.java
openmanage/src/main/java/com/vmware/flowgate/openmanage/job/OpenManageJobService.java

Add unit property for MetricData

---

flowgate-api/src/test/java/com/vmware/flowgate/controller/AssetControllerTest.java
nlyte-worker/src/main/java/com/vmware/flowgate/nlyteworker/scheduler/job/NlyteDataService.java
openmanage/src/main/java/com/vmware/flowgate/openmanage/job/OpenManageJobService.java
poweriq-worker/src/main/java/com/vmware/flowgate/poweriqworker/jobs/PowerIQService.java
poweriq-worker/src/test/java/com/vmware/flowgate/poweriqworker/jobtest/SyncRealTimeDataJobTest.java
vc-worker/src/main/java/com/vmware/flowgate/vcworker/scheduler/job/VCDataService.java

Use new metrics unit to instead of the old

---

make/build.sh

Fix save image issue for build.sh

---

flowgate-api/src/main/java/com/vmware/flowgate/service/AssetService.java
flowgate-api/src/test/java/com/vmware/flowgate/controller/AssetControllerTest.java

Handle temperature metric data

---

vc-worker/src/main/java/com/vmware/flowgate/vcworker/scheduler/job/VCDataService.java
vc-worker/src/test/java/com/vmware/flowgate/vcworker/VCDataServiceTest.java

Populate vc EnergyConsumption Metric Extraidentifier field

---

flowgate-api/src/test/java/com/vmware/flowgate/controller/AssetControllerTest.java

Update Api doc

---

docs/upgradeFrom1.1.2To1.2.md
make/build.sh
make/flowgate_init.sh
make/maven-docker-build/build.sh
make/upgrade.sh

Script for upgrading flowgate from 1.1.2 to 1.2.0

---

flowgate-api/pom.xml
vro-worker/pom.xml

Fix security vulnerability for guava

---

flowgate-api/pom.xml
vro-worker/pom.xml

Upgrade guava to 30.0

---

flowgate-api/src/main/java/com/vmware/flowgate/service/AssetService.java

A part of common methods

---

flowgate-common/src/main/java/com/vmware/flowgate/common/model/TranslateContext.java

Add TranslateContext

---

flowgate-common/src/main/java/com/vmware/flowgate/common/model/TranslateContext.java

Change TranslateContext formulars -> formula

---

flowgate-common/src/main/java/com/vmware/flowgate/common/MetricName.java

Add formula keys for PDU asset

---

flowgate-api/pom.xml
flowgate-api/src/main/java/com/vmware/flowgate/service/AssetService.java
flowgate-api/src/main/java/com/vmware/flowgate/service/TranslateFunctionService.java
flowgate-api/src/test/java/com/vmware/flowgate/service/TranslateFunctionServiceTest.java
flowgate-common/src/main/java/com/vmware/flowgate/common/model/TranslateContext.java
flowgate-common/src/main/java/com/vmware/flowgate/common/model/ValueUnit.java

Add Translate function

---

flowgate-api/src/main/java/com/vmware/flowgate/service/AssetService.java
flowgate-api/src/main/java/com/vmware/flowgate/service/CompareValueUnitByTime.java

Prepare translate context for server

---

flowgate-api/src/main/java/com/vmware/flowgate/service/AssetService.java
flowgate-api/src/main/java/com/vmware/flowgate/service/TranslateFunctionService.java
flowgate-api/src/test/java/com/vmware/flowgate/controller/AssetControllerTest.java
flowgate-api/src/test/java/com/vmware/flowgate/service/TranslateFunctionServiceTest.java
flowgate-common/src/main/java/com/vmware/flowgate/common/MetricKeyName.java

Remove pdu metric name format from MetricKeyName

---

flowgate-api/src/main/java/com/vmware/flowgate/service/TranslateFunctionService.java

Optimize TranslateFunction

---

flowgate-api/src/main/java/com/vmware/flowgate/service/AssetService.java
flowgate-api/src/test/java/com/vmware/flowgate/controller/AssetControllerTest.java
flowgate-common/src/main/java/com/vmware/flowgate/common/FlowgateConstant.java

get metrics data for pdu

---

flowgate-api/src/main/java/com/vmware/flowgate/controller/AssetController.java
flowgate-api/src/main/java/com/vmware/flowgate/service/AssetService.java
flowgate-api/src/test/java/com/vmware/flowgate/controller/AssetControllerTest.java

Modify the getAssetMetricsData API to obtain current metric data for server

---

vc-worker/src/test/java/com/vmware/flowgate/vcworker/VCDataServiceTest.java

Add test case for server power

---

flowgate-api/pom.xml

Upgrade the commons-io to 2.7 to fix the security vulnerability

---

flowgate-api/src/main/java/com/vmware/flowgate/service/AssetService.java
flowgate-api/src/test/java/com/vmware/flowgate/controller/AssetControllerTest.java

Modify the getAssetMetricsData API to obtain current metric data for pdu

---

flowgate-api/src/main/java/com/vmware/flowgate/service/AssetService.java
flowgate-api/src/main/java/com/vmware/flowgate/service/CompareValueUnit.java
flowgate-api/src/test/java/com/vmware/flowgate/util/FilterServerEnergyConsumptionTest.java

filter energy consumption

---

flowgate-api/src/main/java/com/vmware/flowgate/service/AssetService.java
flowgate-api/src/main/java/com/vmware/flowgate/service/TranslateFunctionService.java
flowgate-api/src/test/java/com/vmware/flowgate/controller/AssetControllerTest.java

Get metric datas by other asset

---

aggregator/src/main/java/com/vmware/flowgate/aggregator/scheduler/job/AggregatorService.java
aggregator/src/test/java/com/vmware/flowgate/aggregator/AggregatorServiceTest.java
nlyte-worker/src/main/java/com/vmware/flowgate/nlyteworker/scheduler/job/NlyteDataService.java
nlyte-worker/src/test/java/com/vmware/flowgate/nlyteworker/testjob/SycnRealTimeDataJobTest.java
poweriq-worker/src/main/java/com/vmware/flowgate/poweriqworker/jobs/PowerIQService.java
poweriq-worker/src/test/java/com/vmware/flowgate/poweriqworker/jobtest/SyncPduAssetJobTest.java

Save pdu formula

---

poweriq-worker/src/main/java/com/vmware/flowgate/poweriqworker/jobs/PowerIQService.java
poweriq-worker/src/test/java/com/vmware/flowgate/poweriqworker/jobtest/SyncSensorMetaDataJobTest.java

Save sensor formula

---

flowgate-api/src/main/java/com/vmware/flowgate/service/AssetService.java
flowgate-api/src/test/java/com/vmware/flowgate/controller/AssetControllerTest.java

Modify the getAssetMetricsData API to obtain current metric data for other

---

flowgate-api/src/docs/asciidocs/api-guide.adoc
flowgate-api/src/main/java/com/vmware/flowgate/controller/AssetController.java
flowgate-api/src/main/java/com/vmware/flowgate/service/AssetService.java
flowgate-api/src/main/java/com/vmware/flowgate/service/CompareValueUnit.java
flowgate-api/src/test/java/com/vmware/flowgate/controller/AssetControllerTest.java
flowgate-api/src/test/java/com/vmware/flowgate/util/FilterServerEnergyConsumptionTest.java

Add a new API to get metric duration data

---

flowgate-api/src/docs/asciidocs/api-guide.adoc
flowgate-api/src/main/java/com/vmware/flowgate/controller/AssetController.java
flowgate-api/src/test/java/com/vmware/flowgate/controller/AssetControllerTest.java

Update api doc getAssetMetricsData API description

---

ui/package-lock.json
ui/package.json

Fix conflicting dependencies for xmlhttprequest-ssl in ui project

---

vc-worker/pom.xml

Upgrade bcprov-jdk15on from 1.65.01 to 1.67 in /vc-worker

---

vc-worker/src/main/java/com/vmware/flowgate/vcworker/scheduler/job/VCDataService.java
vc-worker/src/test/java/com/vmware/flowgate/vcworker/VCDataServiceTest.java

Fix missing vc-worker formula

---

vc-worker/src/main/java/com/vmware/flowgate/vcworker/scheduler/job/VCDataService.java
vc-worker/src/test/java/com/vmware/flowgate/vcworker/VCDataServiceTest.java

Fix vc-worker cannot get metricid and cause error

---

ui/src/app/pages/facility/component/dcim/dcim-edit/dcim-edit.component.ts

Display type name when update openmanage integrations

---

ui/src/app/pages/servermapping/servermapping.component.ts

Fix can't cancel mapping

---

flowgate-api/src/main/java/com/vmware/flowgate/service/ServerValidationService.java
flowgate-api/src/test/java/com/vmware/flowgate/controller/FacilitySoftwareControllerTest.java

Add validation for openmanage host ip

---

docs/installation_guide.md

Enhance instalation_guide

---

openmanage/src/main/java/com/vmware/flowgate/openmanage/datamodel/DevicePower.java
openmanage/src/main/java/com/vmware/flowgate/openmanage/datamodel/DeviceTemperature.java
openmanage/src/main/java/com/vmware/flowgate/openmanage/job/OpenManageJobService.java
openmanage/src/test/java/com/vmware/flowgate/openmanage/jobtest/OpenManageJobTest.java

Change value type to String for openmanage metric

---

flowgate-api/src/main/java/com/vmware/flowgate/service/AssetService.java
flowgate-api/src/test/java/com/vmware/flowgate/controller/AssetControllerTest.java

Fix outlets is null

---

flowgate-api/src/main/java/com/vmware/flowgate/service/ServerValidationService.java

Throw excepted error message when create sddc integration failed

---

flowgate-api/src/main/java/com/vmware/flowgate/service/AssetService.java

Check host metric formula is null

---

flowgate-api/src/main/java/com/vmware/flowgate/service/AssetService.java
flowgate-api/src/test/java/com/vmware/flowgate/util/FilterServerEnergyConsumptionTest.java

Filter enery consumption by since time

---

flowgate-api/src/test/java/com/vmware/flowgate/controller/AssetControllerTest.java
flowgate-common/src/main/java/com/vmware/flowgate/common/model/Asset.java

Check the formula string is null

---

flowgate-api/src/test/java/com/vmware/flowgate/controller/AssetControllerTest.java

Add a test case about host usage formula

---

flowgate-common/pom.xml

Set the flowgate-common module to compile with jdk1.8

---

adapter-sample/pom.xml

Updata adapter-sample pom flowgate.version

---

docs/adapter_guide.md

Update adapter guide document

---

docs/adapter_guide.md

Update adapter guide document to v1.2.0

---

ui/src/app/pages/facility/component/dcim/dcim-add/dcim-add.component.html
ui/src/app/pages/facility/component/dcim/dcim-edit/dcim-edit.component.html

Remove invalid unit in adavance setting form

---

ui/src/app/pages/facility/component/dcim/dcim-add/dcim-add.component.html
ui/src/app/pages/facility/component/dcim/dcim-edit/dcim-edit.component.html

Remove invalid unit in adavance setting form(v1.2.0)

---

flowgate-api/pom.xml
vro-worker/pom.xml

Upgrade httpclient to 4.5.13 to fix a security vulnerability

---

.github/workflows/aggregator.yml
.github/workflows/flowgate-api.yml
.github/workflows/infoblox-worker.yml
.github/workflows/labsdb-worker.yml
.github/workflows/management.yml
.github/workflows/nlyte-worker.yml
.github/workflows/openmanage.yml
.github/workflows/poweriq-worker.yml
.github/workflows/vc-worker.yml
.github/workflows/vro-worker.yml
aggregator/pom.xml
common-restclient/pom.xml
flowgate-api/pom.xml
flowgate-common/pom.xml
infoblox-worker/pom.xml
labsdb-worker/pom.xml
management/pom.xml
nlyte-worker/pom.xml
poweriq-worker/pom.xml
vc-worker/pom.xml
vro-worker/pom.xml
worker-jobs/pom.xml

Upgrade JDK from 8 to 11

---

make/maven-docker-build/DockerfileUI
make/maven-docker-build/buildui.sh
make/maven-docker-build/buildui.yml

Update ui build base image

---

make/baseimage/Dockerfile
make/maven-docker-build/Dockerfile

Upgrade image jdk

---

ui/package-lock.json
ui/package.json

Bump webpack from 5.70.0 to 5.76.0 in /ui

---

ui/package-lock.json

Bump lodash.template from 3.6.2 to 4.5.0 in /ui

---

ui/karma.conf.js
ui/package-lock.json
ui/package.json

Uninstall devDependency: karma-remap-istanbul.
